/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef TESTPROJECT_VERSION_H
#define TESTPROJECT_VERSION_H

#define TESTPROJECT_VERSION_MAJOR 1
#define TESTPROJECT_VERSION_MINOR 0
#define TESTPROJECT_VERSION_PATCH 0
#define TESTPROJECT_VERSION_STR "1.0.0"

#endif // TESTPROJECT_VERSION_H
